#!/bin/sh
# properties = {"type": "single", "rule": "mergeAlign", "local": false, "input": ["/work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7711_FNF_Ankle_1_RG.bam", "/work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7717_FNF_Ankle_1_RG.bam", "/work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7735_FNF_Ankle_1_RG.bam", "/work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7754_FNF_Ankle_1_RG.bam", "/work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7755_FNF_Ankle_1_RG.bam", "/work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7763_FNF_Ankle_1_RG.bam", "/work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7765_FNF_Ankle_1_RG.bam", "/work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7769_FNF_Ankle_1_RG.bam", "/work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7771_FNF_Ankle_1_RG.bam", "/work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7775_FNF_Ankle_1_RG.bam", "/work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7778FE_CTL_Femur_1_RG.bam", "/work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7780_FNF_Ankle_1_RG.bam", "/work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7781_FNF_Ankle_1_RG.bam", "/work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7785_FNF_Ankle_1_RG.bam", "/work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7786_FNF_Ankle_1_RG.bam"], "output": ["rna_output/signals/Ankle/mergedAlign/FNF_sorted.bam", "rna_output/signals/Ankle/mergedAlign/FNF_sorted.bam.bai", "rna_output/signals/Ankle/mergedAlign/FNF_stats.txt"], "wildcards": {"tissue": "Ankle", "cond": "FNF"}, "params": {"samtools_version": "1.21"}, "log": ["rna_output/logs/mergedAligned_Ankle_FNF.err"], "threads": 1, "resources": {}, "jobid": 62, "cluster": {"name": "mergeAlign,cond=FNF,tissue=Ankle", "partition": "general", "time": 4320, "cpusPerTask": "1", "memPerCpu": "8G", "nodes": 1, "ntasks": 1, "output": "output/logs_slurm/mergeAlign.cond=FNF,tissue=Ankle.62.out", "error": "output/logs_slurm/mergeAlign.cond=FNF,tissue=Ankle.62.err"}}
cd /work/users/s/e/seyoun/CQTL_AI && \
/work/users/s/e/seyoun/CQTL_AI/env/bin/python3 \
-m snakemake rna_output/signals/Ankle/mergedAlign/FNF_sorted.bam --snakefile /work/users/s/e/seyoun/CQTL_AI/snakefiles/RNA_signal_track.smk \
--force -j --keep-target-files --keep-remote \
--wait-for-files /work/users/s/e/seyoun/CQTL_AI/.snakemake/tmp.vhcty_f8 /work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7711_FNF_Ankle_1_RG.bam /work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7717_FNF_Ankle_1_RG.bam /work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7735_FNF_Ankle_1_RG.bam /work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7754_FNF_Ankle_1_RG.bam /work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7755_FNF_Ankle_1_RG.bam /work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7763_FNF_Ankle_1_RG.bam /work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7765_FNF_Ankle_1_RG.bam /work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7769_FNF_Ankle_1_RG.bam /work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7771_FNF_Ankle_1_RG.bam /work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7775_FNF_Ankle_1_RG.bam /work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7778FE_CTL_Femur_1_RG.bam /work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7780_FNF_Ankle_1_RG.bam /work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7781_FNF_Ankle_1_RG.bam /work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7785_FNF_Ankle_1_RG.bam /work/users/s/e/seyoun/CQTL_AI/rna_output/align/CQTL_AM7786_FNF_Ankle_1_RG.bam --latency-wait 500 \
 --attempt 1 --force-use-threads \
--wrapper-prefix https://github.com/snakemake/snakemake-wrappers/raw/ \
 --configfiles /work/users/s/e/seyoun/CQTL_AI/config/RNAconfig.yaml -p --allowed-rules mergeAlign --nocolor --notemp --no-hooks --nolock \
--mode 2  && exit 0 || exit 1

