## Path to sample sheet
samplesheet: 'atac_samplesheet2.txt'

## List columns to concatenate for file names 
## (or indicate a single Name column, i.e. fileNamesFrom: ['Name'])
fileNamesFrom: ['Proj','Donor','Condition','Tissue','Protocol_notes']

## List columns to group (i.e. any columns left out will become part of the same group)
## set mergeBy: '' for no merging 
mergeBy: ['Proj','Donor','Condition','Tissue','Protocol_notes']

## Indicate whether to create stranded signal tracks
stranded: False

##Blacklistfile
blacklist: '/work/users/s/e/seyoun/CQTL_AI/external/blacklist_region'

#BWAindex
bwa_index: '/users/s/e/seyoun/Ref/genome/bwa_idx/hg38'

#vcf_raw
vcf: '/work/users/s/e/seyoun/CQTL_AI/Genopipe/output/vcf/CQTL_COA9_10_ALL_qc.vcf.gz'
vcf_copy: '/work/users/s/e/seyoun/CQTL_AI/output/geno/cQTL_21_filtered.vcf.gz'

#WASP
wasp_dir: '/nas/longleaf/rhel8/apps/wasp/2023-02/WASP'
chrom_size: '/proj/phanstiel_lab/References/chromSizes/hg38_chromSizes_filt.txt'

#Sample exclude
samples_to_omit: ['AM7717']
vcf_sample_exclude: "0_6_chQTL_AM7366_D,0_16_chQTL_AM7636_D_1"

exclude_options:
  exclude_replicates: True
  exclude_synovium: True
  exclude_femur: True

#Need for the verifyvamID preprocess
base_dir: "/work/users/s/e/seyoun/CQTL_AI"

#verifybamid
verifybamid: '/users/s/e/seyoun/tools/verifyBamID_1.1.3/verifyBamID/bin/verifyBamID'

#atacqv
tssextension: '2000'

## Software versions
fastqcVers: "0.12.1"
trim_galore: "0.6.7"
python: "3.9.6"
r: "4.4.0"
bwaVers: "0.7.17"
samtoolsVers: "1.21"
javaVers: "17.0.2"
waspVer: "2023-02"
picardVers: "2.26.11"
ataqvVers: "1.0.0"



