__default__:
  name: "{rule},{wildcards}" # -J
  partition: general # -p
  time: 4320 # -t
  cpusPerTask: "{threads}" # -c
  memPerCpu: 4G # --mem-per-cpu
  nodes: 1
  ntasks: 1
  output: "rna_output/logs_slurm/{rule}.{wildcards}.{jobid}.out"
  error: "rna_output/logs_slurm/{rule}.{wildcards}.{jobid}.err"

## Multi-threaded / High-memory Rules

align:
  memPerCpu: 16G

reheader:
 memPerCpu: 8G

mark_duplicates:
  memPerCpu: 10G

collect_insert_size_metrics:
  memPerCpu: 6G

add_read_groups:
  memPerCpu: 6G

verifybamid:
  memPerCpu: 15G
  time: "11-00:00:00"

quant:
  memPerCpu: 4G

multiqc:
  memPerCpu: 4G

signal:
  memPerCpu: 4G

mergeSignal:
  memPerCpu: 8G
  time: "11-00:00:00"

mergeForwardSignal:
  memPerCpu: 16G
  time: "11-00:00:00"

mergeReverseSignal:
  memPerCpu: 16G
  time: "11-00:00:00"

mergeAlign:
  memPerCpu: 8G

find_intersecting_snps:
  memPerCpu: 16G

remap_wasp_reads:
  memPerCpu: 16G

filter_remapped_reads:
  memPerCpu: 32G

merge:
  memPerCpu: 6G





